# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoCreateBUSLabel.ui'
#
# Created: Thu Dec 15 12:01:20 2016
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 451)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.height = QtGui.QLineEdit(self.widget)
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pitch = QtGui.QLineEdit(self.widget)
        self.pitch.setObjectName("pitch")
        self.gridLayout.addWidget(self.pitch, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.justification = QtGui.QComboBox(self.widget)
        self.justification.setObjectName("justification")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.justification.addItem("")
        self.gridLayout.addWidget(self.justification, 7, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.interval = QtGui.QComboBox(self.widget)
        self.interval.setObjectName("interval")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.gridLayout.addWidget(self.interval, 2, 1, 1, 1)
        self.rotation = QtGui.QComboBox(self.widget)
        self.rotation.setObjectName("rotation")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.rotation.addItem("")
        self.gridLayout.addWidget(self.rotation, 6, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.direction = QtGui.QComboBox(self.widget)
        self.direction.setObjectName("direction")
        self.direction.addItem("")
        self.direction.addItem("")
        self.direction.addItem("")
        self.direction.addItem("")
        self.gridLayout.addWidget(self.direction, 3, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.font = QtGui.QComboBox(self.widget)
        self.font.setObjectName("font")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.gridLayout.addWidget(self.font, 5, 1, 1, 1)
        self.label_label = QtGui.QLabel(self.widget)
        self.label_label.setObjectName("label_label")
        self.gridLayout.addWidget(self.label_label, 0, 0, 1, 1)
        self.label = QtGui.QLineEdit(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.createpin = QtGui.QCheckBox(self.groupBox)
        self.createpin.setChecked(True)
        self.createpin.setObjectName("createpin")
        self.gridLayout_2.addWidget(self.createpin, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(33, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pinwidth = QtGui.QLineEdit(self.groupBox)
        self.pinwidth.setObjectName("pinwidth")
        self.gridLayout_2.addWidget(self.pinwidth, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.pinheight = QtGui.QLineEdit(self.groupBox)
        self.pinheight.setObjectName("pinheight")
        self.gridLayout_2.addWidget(self.pinheight, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.pininout = QtGui.QComboBox(self.groupBox)
        self.pininout.setObjectName("pininout")
        self.pininout.addItem("")
        self.pininout.addItem("")
        self.pininout.addItem("")
        self.gridLayout_2.addWidget(self.pininout, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok = QtGui.QPushButton(self.centralwidget)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.apply = QtGui.QPushButton(self.centralwidget)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.cancel = QtGui.QPushButton(self.centralwidget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ok, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.cancel, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.label, self.pitch)
        MainWindow.setTabOrder(self.pitch, self.interval)
        MainWindow.setTabOrder(self.interval, self.direction)
        MainWindow.setTabOrder(self.direction, self.height)
        MainWindow.setTabOrder(self.height, self.font)
        MainWindow.setTabOrder(self.font, self.rotation)
        MainWindow.setTabOrder(self.rotation, self.justification)
        MainWindow.setTabOrder(self.justification, self.createpin)
        MainWindow.setTabOrder(self.createpin, self.pinwidth)
        MainWindow.setTabOrder(self.pinwidth, self.pinheight)
        MainWindow.setTabOrder(self.pinheight, self.ok)
        MainWindow.setTabOrder(self.ok, self.apply)
        MainWindow.setTabOrder(self.apply, self.cancel)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "autoCreateLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.height.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pitch.setText(QtGui.QApplication.translate("MainWindow", "2.8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Justification", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(0, QtGui.QApplication.translate("MainWindow", "lowerCenter", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(1, QtGui.QApplication.translate("MainWindow", "lowerLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(2, QtGui.QApplication.translate("MainWindow", "centerLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(3, QtGui.QApplication.translate("MainWindow", "upperLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(4, QtGui.QApplication.translate("MainWindow", "centerCenter", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(5, QtGui.QApplication.translate("MainWindow", "upperCenter", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(6, QtGui.QApplication.translate("MainWindow", "lowerRight", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(7, QtGui.QApplication.translate("MainWindow", "centerRight", None, QtGui.QApplication.UnicodeUTF8))
        self.justification.setItemText(8, QtGui.QApplication.translate("MainWindow", "upperRight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.interval.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.interval.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.interval.setItemText(2, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.interval.setItemText(3, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(0, QtGui.QApplication.translate("MainWindow", "R0", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(1, QtGui.QApplication.translate("MainWindow", "R90", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(2, QtGui.QApplication.translate("MainWindow", "R180", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(3, QtGui.QApplication.translate("MainWindow", "R270", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(4, QtGui.QApplication.translate("MainWindow", "MY", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(5, QtGui.QApplication.translate("MainWindow", "MYR90", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(6, QtGui.QApplication.translate("MainWindow", "MX", None, QtGui.QApplication.UnicodeUTF8))
        self.rotation.setItemText(7, QtGui.QApplication.translate("MainWindow", "MXR90", None, QtGui.QApplication.UnicodeUTF8))
        self.direction.setItemText(0, QtGui.QApplication.translate("MainWindow", "LeftToRight", None, QtGui.QApplication.UnicodeUTF8))
        self.direction.setItemText(1, QtGui.QApplication.translate("MainWindow", "RightToLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.direction.setItemText(2, QtGui.QApplication.translate("MainWindow", "UpToDown", None, QtGui.QApplication.UnicodeUTF8))
        self.direction.setItemText(3, QtGui.QApplication.translate("MainWindow", "DownToUp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Rotation", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(0, QtGui.QApplication.translate("MainWindow", "stick", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(1, QtGui.QApplication.translate("MainWindow", "euroStyle", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(2, QtGui.QApplication.translate("MainWindow", "gothic", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(3, QtGui.QApplication.translate("MainWindow", "math", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(4, QtGui.QApplication.translate("MainWindow", "roman", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(5, QtGui.QApplication.translate("MainWindow", "script", None, QtGui.QApplication.UnicodeUTF8))
        self.font.setItemText(6, QtGui.QApplication.translate("MainWindow", "swedish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_label.setText(QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "BUS<0:1023>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "PIN", None, QtGui.QApplication.UnicodeUTF8))
        self.createpin.setText(QtGui.QApplication.translate("MainWindow", "createPIN", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "width", None, QtGui.QApplication.UnicodeUTF8))
        self.pinwidth.setText(QtGui.QApplication.translate("MainWindow", "0.29", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "height", None, QtGui.QApplication.UnicodeUTF8))
        self.pinheight.setText(QtGui.QApplication.translate("MainWindow", "0.29", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "inout", None, QtGui.QApplication.UnicodeUTF8))
        self.pininout.setItemText(0, QtGui.QApplication.translate("MainWindow", "input", None, QtGui.QApplication.UnicodeUTF8))
        self.pininout.setItemText(1, QtGui.QApplication.translate("MainWindow", "output", None, QtGui.QApplication.UnicodeUTF8))
        self.pininout.setItemText(2, QtGui.QApplication.translate("MainWindow", "inputOutput", None, QtGui.QApplication.UnicodeUTF8))
        self.ok.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.apply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

