# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'libraryBrowser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(770, 686)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.ok = QtGui.QPushButton(self.centralwidget)
        self.ok.setMaximumSize(QtCore.QSize(16777215, 27))
        self.ok.setObjectName(_fromUtf8("ok"))
        self.horizontalLayout_5.addWidget(self.ok)
        self.cancel = QtGui.QPushButton(self.centralwidget)
        self.cancel.setMaximumSize(QtCore.QSize(16777215, 27))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.horizontalLayout_5.addWidget(self.cancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.splitter = QtGui.QSplitter(self.frame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.Glibrary = QtGui.QGroupBox(self.splitter)
        self.Glibrary.setObjectName(_fromUtf8("Glibrary"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Glibrary)
        self.verticalLayout.setContentsMargins(3, -1, 3, 9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.Glibrary)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.libfilter = QtGui.QLineEdit(self.Glibrary)
        self.libfilter.setObjectName(_fromUtf8("libfilter"))
        self.horizontalLayout.addWidget(self.libfilter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.library = QtGui.QListWidget(self.Glibrary)
        self.library.setObjectName(_fromUtf8("library"))
        self.verticalLayout.addWidget(self.library)
        self.Gcategory = QtGui.QGroupBox(self.splitter)
        self.Gcategory.setObjectName(_fromUtf8("Gcategory"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Gcategory)
        self.verticalLayout_2.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.Gcategory)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.catfilter = QtGui.QLineEdit(self.Gcategory)
        self.catfilter.setEnabled(False)
        self.catfilter.setAutoFillBackground(True)
        self.catfilter.setObjectName(_fromUtf8("catfilter"))
        self.horizontalLayout_2.addWidget(self.catfilter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.category = QtGui.QListWidget(self.Gcategory)
        self.category.setObjectName(_fromUtf8("category"))
        self.verticalLayout_2.addWidget(self.category)
        self.Gcell = QtGui.QGroupBox(self.splitter)
        self.Gcell.setObjectName(_fromUtf8("Gcell"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Gcell)
        self.verticalLayout_3.setContentsMargins(3, -1, -1, 3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.Gcell)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cellfilter = QtGui.QLineEdit(self.Gcell)
        self.cellfilter.setObjectName(_fromUtf8("cellfilter"))
        self.horizontalLayout_3.addWidget(self.cellfilter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.cell = QtGui.QListWidget(self.Gcell)
        self.cell.setObjectName(_fromUtf8("cell"))
        self.verticalLayout_3.addWidget(self.cell)
        self.Gview = QtGui.QGroupBox(self.splitter)
        self.Gview.setObjectName(_fromUtf8("Gview"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Gview)
        self.verticalLayout_4.setContentsMargins(3, -1, -1, 3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.Gview)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.viewfilter = QtGui.QLineEdit(self.Gview)
        self.viewfilter.setEnabled(False)
        self.viewfilter.setAutoFillBackground(True)
        self.viewfilter.setObjectName(_fromUtf8("viewfilter"))
        self.horizontalLayout_4.addWidget(self.viewfilter)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.view = QtGui.QListWidget(self.Gview)
        self.view.setObjectName(_fromUtf8("view"))
        self.verticalLayout_4.addWidget(self.view)
        self.verticalLayout_5.addWidget(self.splitter)
        self.verticalLayout_6.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ok, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.ok.setText(_translate("MainWindow", "OK", None))
        self.cancel.setText(_translate("MainWindow", "Cancel", None))
        self.Glibrary.setTitle(_translate("MainWindow", "Library", None))
        self.label.setText(_translate("MainWindow", "Filter", None))
        self.Gcategory.setTitle(_translate("MainWindow", "Category", None))
        self.label_2.setText(_translate("MainWindow", "Filter", None))
        self.catfilter.setPlaceholderText(_translate("MainWindow", "Disabled", None))
        self.Gcell.setTitle(_translate("MainWindow", "Cell", None))
        self.label_3.setText(_translate("MainWindow", "Filter", None))
        self.Gview.setTitle(_translate("MainWindow", "View", None))
        self.label_4.setText(_translate("MainWindow", "Filter", None))
        self.viewfilter.setPlaceholderText(_translate("MainWindow", "Disabled", None))

