# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PowerExtraction.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(707, 602)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.TabWidget = QtGui.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 20))
        self.label.setMaximumSize(QtCore.QSize(80, 20))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.rundir = QtGui.QLineEdit(self.tab1)
        self.rundir.setObjectName(_fromUtf8("rundir"))
        self.horizontalLayout_5.addWidget(self.rundir)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_5)
        self.dirbrowser = QtGui.QPushButton(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirbrowser.sizePolicy().hasHeightForWidth())
        self.dirbrowser.setSizePolicy(sizePolicy)
        self.dirbrowser.setObjectName(_fromUtf8("dirbrowser"))
        self.horizontalLayout_27.addWidget(self.dirbrowser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.line = QtGui.QFrame(self.tab1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 20))
        self.label_2.setMaximumSize(QtCore.QSize(80, 20))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.libname = QtGui.QLineEdit(self.tab1)
        self.libname.setObjectName(_fromUtf8("libname"))
        self.horizontalLayout_2.addWidget(self.libname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(80, 20))
        self.label_3.setMaximumSize(QtCore.QSize(80, 20))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cellname = QtGui.QLineEdit(self.tab1)
        self.cellname.setObjectName(_fromUtf8("cellname"))
        self.horizontalLayout.addWidget(self.cellname)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(80, 20))
        self.label_4.setMaximumSize(QtCore.QSize(80, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.viewname = QtGui.QLineEdit(self.tab1)
        self.viewname.setObjectName(_fromUtf8("viewname"))
        self.horizontalLayout_3.addWidget(self.viewname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_29.addLayout(self.verticalLayout_2)
        self.celllist = QtGui.QPushButton(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.celllist.sizePolicy().hasHeightForWidth())
        self.celllist.setSizePolicy(sizePolicy)
        self.celllist.setMinimumSize(QtCore.QSize(0, 83))
        self.celllist.setMaximumSize(QtCore.QSize(16777215, 83))
        self.celllist.setObjectName(_fromUtf8("celllist"))
        self.horizontalLayout_29.addWidget(self.celllist)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.line_2 = QtGui.QFrame(self.tab1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.gdsfilecheck = QtGui.QCheckBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdsfilecheck.sizePolicy().hasHeightForWidth())
        self.gdsfilecheck.setSizePolicy(sizePolicy)
        self.gdsfilecheck.setMinimumSize(QtCore.QSize(80, 20))
        self.gdsfilecheck.setMaximumSize(QtCore.QSize(80, 20))
        self.gdsfilecheck.setObjectName(_fromUtf8("gdsfilecheck"))
        self.horizontalLayout_51.addWidget(self.gdsfilecheck)
        self.gdsfile = QtGui.QLineEdit(self.tab1)
        self.gdsfile.setObjectName(_fromUtf8("gdsfile"))
        self.horizontalLayout_51.addWidget(self.gdsfile)
        self.gdsbrowser = QtGui.QPushButton(self.tab1)
        self.gdsbrowser.setObjectName(_fromUtf8("gdsbrowser"))
        self.horizontalLayout_51.addWidget(self.gdsbrowser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_51)
        self.line_7 = QtGui.QFrame(self.tab1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 20))
        self.label_7.setMaximumSize(QtCore.QSize(80, 20))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.extnetname = QtGui.QLineEdit(self.tab1)
        self.extnetname.setObjectName(_fromUtf8("extnetname"))
        self.horizontalLayout_6.addWidget(self.extnetname)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.reflibcheck = QtGui.QCheckBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reflibcheck.sizePolicy().hasHeightForWidth())
        self.reflibcheck.setSizePolicy(sizePolicy)
        self.reflibcheck.setMinimumSize(QtCore.QSize(80, 20))
        self.reflibcheck.setMaximumSize(QtCore.QSize(80, 20))
        self.reflibcheck.setObjectName(_fromUtf8("reflibcheck"))
        self.horizontalLayout_12.addWidget(self.reflibcheck)
        self.reflib = QtGui.QLineEdit(self.tab1)
        self.reflib.setObjectName(_fromUtf8("reflib"))
        self.horizontalLayout_12.addWidget(self.reflib)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.hiercheck = QtGui.QCheckBox(self.tab1)
        self.hiercheck.setObjectName(_fromUtf8("hiercheck"))
        self.horizontalLayout_13.addWidget(self.hiercheck)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.tab1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.date = QtGui.QLineEdit(self.tab1)
        self.date.setObjectName(_fromUtf8("date"))
        self.horizontalLayout_7.addWidget(self.date)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.label_33 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(80, 20))
        self.label_33.setMaximumSize(QtCore.QSize(80, 20))
        self.label_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_50.addWidget(self.label_33)
        self.techfile = QtGui.QLineEdit(self.tab1)
        self.techfile.setObjectName(_fromUtf8("techfile"))
        self.horizontalLayout_50.addWidget(self.techfile)
        self.horizontalLayout_49.addLayout(self.horizontalLayout_50)
        self.techbrowser = QtGui.QPushButton(self.tab1)
        self.techbrowser.setObjectName(_fromUtf8("techbrowser"))
        self.horizontalLayout_49.addWidget(self.techbrowser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_49)
        self.line_5 = QtGui.QFrame(self.tab1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.groupBox = QtGui.QGroupBox(self.tab1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(40, 20))
        self.label_16.setMaximumSize(QtCore.QSize(80, 20))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.P1 = QtGui.QLineEdit(self.groupBox)
        self.P1.setObjectName(_fromUtf8("P1"))
        self.horizontalLayout_4.addWidget(self.P1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 20))
        self.label_11.setMaximumSize(QtCore.QSize(40, 20))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.M1 = QtGui.QLineEdit(self.groupBox)
        self.M1.setObjectName(_fromUtf8("M1"))
        self.horizontalLayout_8.addWidget(self.M1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(40, 20))
        self.label_8.setMaximumSize(QtCore.QSize(40, 20))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.M2 = QtGui.QLineEdit(self.groupBox)
        self.M2.setObjectName(_fromUtf8("M2"))
        self.horizontalLayout_9.addWidget(self.M2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(40, 20))
        self.label_9.setMaximumSize(QtCore.QSize(40, 20))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.M3 = QtGui.QLineEdit(self.groupBox)
        self.M3.setObjectName(_fromUtf8("M3"))
        self.horizontalLayout_10.addWidget(self.M3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 20))
        self.label_10.setMaximumSize(QtCore.QSize(40, 20))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.M4 = QtGui.QLineEdit(self.groupBox)
        self.M4.setObjectName(_fromUtf8("M4"))
        self.horizontalLayout_11.addWidget(self.M4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(40, 20))
        self.label_12.setMaximumSize(QtCore.QSize(40, 20))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.MIM = QtGui.QLineEdit(self.groupBox)
        self.MIM.setObjectName(_fromUtf8("MIM"))
        self.horizontalLayout_14.addWidget(self.MIM)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_29 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(40, 20))
        self.label_29.setMaximumSize(QtCore.QSize(40, 20))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_15.addWidget(self.label_29)
        self.M1TXT = QtGui.QLineEdit(self.groupBox)
        self.M1TXT.setObjectName(_fromUtf8("M1TXT"))
        self.horizontalLayout_15.addWidget(self.M1TXT)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_30 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(40, 20))
        self.label_30.setMaximumSize(QtCore.QSize(40, 20))
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_16.addWidget(self.label_30)
        self.M2TXT = QtGui.QLineEdit(self.groupBox)
        self.M2TXT.setObjectName(_fromUtf8("M2TXT"))
        self.horizontalLayout_16.addWidget(self.M2TXT)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_31 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(40, 20))
        self.label_31.setMaximumSize(QtCore.QSize(40, 20))
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_17.addWidget(self.label_31)
        self.M3TXT = QtGui.QLineEdit(self.groupBox)
        self.M3TXT.setObjectName(_fromUtf8("M3TXT"))
        self.horizontalLayout_17.addWidget(self.M3TXT)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_32 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(40, 20))
        self.label_32.setMaximumSize(QtCore.QSize(40, 20))
        self.label_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_18.addWidget(self.label_32)
        self.M4TXT = QtGui.QLineEdit(self.groupBox)
        self.M4TXT.setObjectName(_fromUtf8("M4TXT"))
        self.horizontalLayout_18.addWidget(self.M4TXT)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_23.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem)
        self.MIMLOC = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MIMLOC.sizePolicy().hasHeightForWidth())
        self.MIMLOC.setSizePolicy(sizePolicy)
        self.MIMLOC.setStyleSheet(_fromUtf8(""))
        self.MIMLOC.setObjectName(_fromUtf8("MIMLOC"))
        self.MIMLOC.addItem(_fromUtf8(""))
        self.MIMLOC.addItem(_fromUtf8(""))
        self.MIMLOC.addItem(_fromUtf8(""))
        self.MIMLOC.addItem(_fromUtf8(""))
        self.MIMLOC.addItem(_fromUtf8(""))
        self.horizontalLayout_35.addWidget(self.MIMLOC)
        self.verticalLayout_8.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(40, 20))
        self.label_17.setMaximumSize(QtCore.QSize(40, 20))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_22.addWidget(self.label_17)
        self.CONT = QtGui.QLineEdit(self.groupBox)
        self.CONT.setObjectName(_fromUtf8("CONT"))
        self.horizontalLayout_22.addWidget(self.CONT)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(40, 20))
        self.label_15.setMaximumSize(QtCore.QSize(40, 20))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_21.addWidget(self.label_15)
        self.VIA1 = QtGui.QLineEdit(self.groupBox)
        self.VIA1.setObjectName(_fromUtf8("VIA1"))
        self.horizontalLayout_21.addWidget(self.VIA1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(40, 20))
        self.label_13.setMaximumSize(QtCore.QSize(40, 20))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_20.addWidget(self.label_13)
        self.VIA2 = QtGui.QLineEdit(self.groupBox)
        self.VIA2.setObjectName(_fromUtf8("VIA2"))
        self.horizontalLayout_20.addWidget(self.VIA2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(40, 20))
        self.label_14.setMaximumSize(QtCore.QSize(40, 20))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_19.addWidget(self.label_14)
        self.VIA3 = QtGui.QLineEdit(self.groupBox)
        self.VIA3.setObjectName(_fromUtf8("VIA3"))
        self.horizontalLayout_19.addWidget(self.VIA3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.run = QtGui.QPushButton(self.tab1)
        self.run.setObjectName(_fromUtf8("run"))
        self.horizontalLayout_30.addWidget(self.run)
        self.quit = QtGui.QPushButton(self.tab1)
        self.quit.setObjectName(_fromUtf8("quit"))
        self.horizontalLayout_30.addWidget(self.quit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_30)
        self.groupBox.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_5.raise_()
        self.line_7.raise_()
        self.hiercheck.raise_()
        self.TabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.strmout_tb = QtGui.QTextBrowser(self.tab2)
        self.strmout_tb.setObjectName(_fromUtf8("strmout_tb"))
        self.verticalLayout_4.addWidget(self.strmout_tb)
        self.TabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.strmout_pl_tb = QtGui.QTextBrowser(self.tab3)
        self.strmout_pl_tb.setObjectName(_fromUtf8("strmout_pl_tb"))
        self.verticalLayout_5.addWidget(self.strmout_pl_tb)
        self.TabWidget.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.caldrc_tb = QtGui.QTextBrowser(self.tab4)
        self.caldrc_tb.setObjectName(_fromUtf8("caldrc_tb"))
        self.verticalLayout_10.addWidget(self.caldrc_tb)
        self.TabWidget.addTab(self.tab4, _fromUtf8(""))
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName(_fromUtf8("tab5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.drc_sum_tb = QtGui.QTextBrowser(self.tab5)
        self.drc_sum_tb.setObjectName(_fromUtf8("drc_sum_tb"))
        self.verticalLayout_11.addWidget(self.drc_sum_tb)
        self.TabWidget.addTab(self.tab5, _fromUtf8(""))
        self.tab6 = QtGui.QWidget()
        self.tab6.setObjectName(_fromUtf8("tab6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.strmin_tb = QtGui.QTextBrowser(self.tab6)
        self.strmin_tb.setObjectName(_fromUtf8("strmin_tb"))
        self.verticalLayout_12.addWidget(self.strmin_tb)
        self.TabWidget.addTab(self.tab6, _fromUtf8(""))
        self.tab7 = QtGui.QWidget()
        self.tab7.setObjectName(_fromUtf8("tab7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab7)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.strmin_pl_tb = QtGui.QTextBrowser(self.tab7)
        self.strmin_pl_tb.setObjectName(_fromUtf8("strmin_pl_tb"))
        self.verticalLayout_13.addWidget(self.strmin_pl_tb)
        self.TabWidget.addTab(self.tab7, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.TabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSession = QtGui.QMenu(self.menubar)
        self.menuSession.setObjectName(_fromUtf8("menuSession"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSaveSession = QtGui.QAction(MainWindow)
        self.actionSaveSession.setObjectName(_fromUtf8("actionSaveSession"))
        self.actionLoadSession = QtGui.QAction(MainWindow)
        self.actionLoadSession.setObjectName(_fromUtf8("actionLoadSession"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuSession.addAction(self.actionSaveSession)
        self.menuSession.addAction(self.actionLoadSession)
        self.menuSession.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSession.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.quit, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.close)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rundir, self.libname)
        MainWindow.setTabOrder(self.libname, self.cellname)
        MainWindow.setTabOrder(self.cellname, self.viewname)
        MainWindow.setTabOrder(self.viewname, self.gdsfile)
        MainWindow.setTabOrder(self.gdsfile, self.extnetname)
        MainWindow.setTabOrder(self.extnetname, self.date)
        MainWindow.setTabOrder(self.date, self.techfile)
        MainWindow.setTabOrder(self.techfile, self.MIMLOC)
        MainWindow.setTabOrder(self.MIMLOC, self.M1)
        MainWindow.setTabOrder(self.M1, self.M3)
        MainWindow.setTabOrder(self.M3, self.M4)
        MainWindow.setTabOrder(self.M4, self.M2TXT)
        MainWindow.setTabOrder(self.M2TXT, self.M3TXT)
        MainWindow.setTabOrder(self.M3TXT, self.M4TXT)
        MainWindow.setTabOrder(self.M4TXT, self.MIM)
        MainWindow.setTabOrder(self.MIM, self.VIA1)
        MainWindow.setTabOrder(self.VIA1, self.VIA2)
        MainWindow.setTabOrder(self.VIA2, self.VIA3)
        MainWindow.setTabOrder(self.VIA3, self.run)
        MainWindow.setTabOrder(self.run, self.quit)
        MainWindow.setTabOrder(self.quit, self.techbrowser)
        MainWindow.setTabOrder(self.techbrowser, self.gdsbrowser)
        MainWindow.setTabOrder(self.gdsbrowser, self.celllist)
        MainWindow.setTabOrder(self.celllist, self.dirbrowser)
        MainWindow.setTabOrder(self.dirbrowser, self.gdsfilecheck)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Power Extraction Window", None))
        self.label.setText(_translate("MainWindow", "RUN DIR", None))
        self.dirbrowser.setText(_translate("MainWindow", "DirBrowser", None))
        self.label_2.setText(_translate("MainWindow", "LibName", None))
        self.label_3.setText(_translate("MainWindow", "CellName", None))
        self.label_4.setText(_translate("MainWindow", "ViewName", None))
        self.celllist.setText(_translate("MainWindow", "CellList", None))
        self.gdsfilecheck.setText(_translate("MainWindow", "GDS File", None))
        self.gdsbrowser.setText(_translate("MainWindow", "FileBrowser", None))
        self.label_7.setText(_translate("MainWindow", "ExtNetName", None))
        self.reflibcheck.setText(_translate("MainWindow", "RefLib", None))
        self.hiercheck.setText(_translate("MainWindow", "-hier", None))
        self.label_5.setText(_translate("MainWindow", "Date", None))
        self.label_33.setText(_translate("MainWindow", "Tech File", None))
        self.techbrowser.setText(_translate("MainWindow", "FileBrowser", None))
        self.groupBox.setTitle(_translate("MainWindow", "Layer Number", None))
        self.label_16.setText(_translate("MainWindow", "POLY", None))
        self.label_11.setText(_translate("MainWindow", "M1", None))
        self.label_8.setText(_translate("MainWindow", "M2", None))
        self.label_9.setText(_translate("MainWindow", "M3", None))
        self.label_10.setText(_translate("MainWindow", "M4", None))
        self.label_12.setText(_translate("MainWindow", "CAP", None))
        self.label_29.setText(_translate("MainWindow", "M1txt", None))
        self.label_30.setText(_translate("MainWindow", "M2txt", None))
        self.label_31.setText(_translate("MainWindow", "M3txt", None))
        self.label_32.setText(_translate("MainWindow", "M4txt", None))
        self.MIMLOC.setItemText(0, _translate("MainWindow", "M1-M2", None))
        self.MIMLOC.setItemText(1, _translate("MainWindow", "M2-M3", None))
        self.MIMLOC.setItemText(2, _translate("MainWindow", "M3-M4", None))
        self.MIMLOC.setItemText(3, _translate("MainWindow", "M4-M5", None))
        self.MIMLOC.setItemText(4, _translate("MainWindow", "P1-P2", None))
        self.label_17.setText(_translate("MainWindow", "CONT", None))
        self.label_15.setText(_translate("MainWindow", "Via1", None))
        self.label_13.setText(_translate("MainWindow", "Via2", None))
        self.label_14.setText(_translate("MainWindow", "Via3", None))
        self.run.setText(_translate("MainWindow", "RUN", None))
        self.quit.setText(_translate("MainWindow", "QUIT", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab1), _translate("MainWindow", "PowerExtract", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab2), _translate("MainWindow", "STRMOUT", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab3), _translate("MainWindow", "PIPO.STRMOUT", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab4), _translate("MainWindow", "CalibreDRC", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab5), _translate("MainWindow", "DRC.sum", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab6), _translate("MainWindow", "STRMIN", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab7), _translate("MainWindow", "PIPO.STRMIN", None))
        self.menuSession.setTitle(_translate("MainWindow", "Session", None))
        self.actionSaveSession.setText(_translate("MainWindow", "SaveSession", None))
        self.actionLoadSession.setText(_translate("MainWindow", "LoadSession", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

